
server.port=8006
spring.application.name=movierecomedation

spring.ai.ollama.base-url=http://localhost:11434

# AI response generation
spring.ai.ollama.chat.model=llama3.2

# Embeddings
spring.ai.ollama.embedding.model=nomic-embed-text